apiVersion: batch/v1
kind: Job
metadata:
  name: single-job
  namespace: test
spec:
  template:
    spec:
      containers:
        - name: worker
          image: tryoo0607/job-test:latest
      restartPolicy: Never
