apiVersion: batch/v1
kind: Job
metadata:
  name: single-pod-job
  namespace: test
spec:
  template:
    spec:
      containers:
        - name: job
          image: tryoo0607/job-test:latest
          command: ["/job-test"]
          env:
            - name: MODE
              value: "fixed"
            - name: ITEMS_FILE
              value: "/data/inputs/list.txt"  
            - name: INPUT_DIR
              value: "/data/inputs"
            - name: OUTPUT_DIR
              value: "/data/outputs"
      restartPolicy: Never