apiVersion: batch/v1
kind: Job
metadata:
  name: fixed-job
  namespace: test
spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      containers:
        - name: worker
          image: tryoo0607/job-test:latest
      restartPolicy: Never
