apiVersion: v1
kind: Service
metadata:
  name: peer-svc
  namespace: test
spec:
  clusterIP: None
  selector:
    app: peer-demo
  publishNotReadyAddresses: true    # ready 전에 노출하기 위해 추가
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: batch/v1
kind: Job
metadata:
  name: peer-job
  namespace: test
spec:
  parallelism: 3
  completions: 3
  completionMode: Indexed

  template:
    metadata:
      labels:
        app: peer-demo 
    spec:
      subdomain: peer-svc
      restartPolicy: Never
      containers:
        - name: app
          image: tryoo0607/job-test:latest
          command: ["/job-test"]
          env:
            - name: MODE
              value: "peer"
            - name: SUBDOMAIN
              value: "peer-svc"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
