apiVersion: batch/v1
kind: Job
metadata:
  name: peer-job
spec:
  completions: 3
  parallelism: 3
  completionMode: Indexed
  template:
    spec:
      subdomain: peer-svc
      hostname: myjob-$(JOB_COMPLETION_INDEX)
      containers:
        - name: job
          image: tryoo0607/job-test:latest
          command: ["/job-test"]
          env:
            - name: MODE
              value: "peer"
            - name: INPUT_DIR
              value: "/data/inputs"
            - name: OUTPUT_DIR
              value: "/data/outputs"
            - name: JOB_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
            - name: TOTAL_PODS
              value: "3"
            - name: SUBDOMAIN
              value: "peer-svc"
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: peer-svc
spec:
  clusterIP: None
  selector:
    job-name: peer-job
  ports:
    - port: 8080
      targetPort: 8080
