apiVersion: v1
kind: Pod
metadata:
  name: random-generator
  namespace: test
  labels:
    app: random-generator
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "while true; do echo $(date) >> /data/log.txt; sleep 5; done"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: random-generator
  namespace: test
spec:
  selector:
    app: random-generator
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: dns-tester
  namespace: test
spec:
  containers:
  - name: dns-test
    image: busybox
    command:
      - sh
      - -c
      - |
        echo "=== DNS TEST ==="
        nslookup random-generator.test.svc.cluster.local
        echo ""
        echo "=== CURL TEST (optional) ==="
        wget -qO- random-generator.test.svc.cluster.local || true
        sleep 3600