apiVersion: v1
kind: Service
metadata:
  name: external-db
  namespace: test
spec:
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-db
  namespace: test
subsets:
- addresses:
  - ip: 1.2.3.4   # 실제 외부 IP로 대체 가능
  ports:
  - port: 5432
---
apiVersion: v1
kind: Pod
metadata:
  name: dns-checker
  namespace: test
spec:
  containers:
  - name: dns-checker
    image: busybox
    command: ["sh", "-c", "sleep 3600"]