apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nodeport
  namespace: test
spec:
  replicas: 3   # control-plane에도 하나 배치되도록 늘림
  selector:
    matchLabels:
      app: nginx-node
  template:
    metadata:
      labels:
        app: nginx-node
    spec:
      tolerations:                # control-plane에도 스케줄링 허용
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector: {}            # 제약 없음 (모든 노드 대상)
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: test
spec:
  type: NodePort
  selector:
    app: nginx-node
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  externalTrafficPolicy: Local
