apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nodeport
  namespace: svc-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-node
  template:
    metadata:
      labels:
        app: nginx-node
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: svc-test
spec:
  type: NodePort
  selector:
    app: nginx-node
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  externalTrafficPolicy: Local
