apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-demo
  namespace: test
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: rolling-demo
  template:
    metadata:
      labels:
        app: rolling-demo
    spec:
      containers:
      - name: web
        image: nginx:1.28
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "v1.28"