apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v1
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: v1
  template:
    metadata:
      labels:
        app: myapp
        version: v1
    spec:
      containers:
      - name: myapp
        image: nginx:1.21
        env:
        - name: VERSION
          value: "v1.21"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v2
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: v2
  template:
    metadata:
      labels:
        app: myapp
        version: v2
    spec:
      containers:
      - name: myapp
        image: nginx:1.28
        env:
        - name: VERSION
          value: "v1.28"