apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: singleton-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: singleton
  template:
    metadata:
      labels:
        app: singleton
    spec:
      containers:
      - name: singleton
        image: busybox
        args: ["sh", "-c", "while true; do echo I am the only one; sleep 5; done"]
