apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-doesnotexist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-doesnotexist
  template:
    metadata:
      labels:
        app: nginx-doesnotexist
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: deprecated
                operator: DoesNotExist
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
