apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-nginx
  namespace: test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: new-nginx
  template:
    metadata:
      labels:
        app: new-nginx
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: new-nginx
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
