apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "NoExecute"
          effect: "NoExecute"
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
