apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota 
  namespace: test
spec:
  hard:
    cpu: "2"
    memory: 3Gi
    pods: "10"
    requests.cpu: "500m"
    requests.memory: 500Mi
    limits.cpu: "1"
    limits.memory: 1Gi 
