apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: test
spec:
  limits:
  - type: Container
    default:
      cpu: "100m"
      memory: "128Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    min:
      cpu: "100m"
      memory: "128Mi"
