apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-lifecycle-volumes
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /lifecycle-volumes/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lifecycle-volumes
  namespace: test
spec:
  volumeName: pv-lifecycle-volumes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: post-start-pre-stop
  namespace: test
  labels:
    app: sigterm-sigkill
spec:
  # nodeSelector:
  #   kubernetes.io/hostname: kind-worker
  # securityContext:
  #   runAsUser: 0
  #   runAsGroup: 0
  terminationGracePeriodSeconds: 10
  containers:
  - name: post-start-pre-stop
    image: tryoo0607/pod-lifecycle-test:latest
    lifecycle:
      postStart:
        exec:
          command:
            [
              "/bin/sh",
              "-c",
              "echo \"[postStart] $(date) 컨테이너 시작됨\" | tee -a /var/log/hooks/hooks.log"
            ]
      preStop:
        exec:
          command:
            [
              "/bin/sh",
              "-c",
              "echo \"[preStop] $(date) 종료 준비 시작\" | tee -a /var/log/hooks/hooks.log; sleep 5; echo \"[preStop] $(date) 종료 완료\" | tee -a /var/log/hooks/hooks.log"
            ]
    volumeMounts:
    - name: lifecycle-volumes
      mountPath: /var/log/hooks
  volumes:
  - name: lifecycle-volumes
    persistentVolumeClaim:
      claimName: pvc-lifecycle-volumes