apiVersion: v1
kind: Pod
metadata:
  name: startup-probe
  labels:
    app: probe-test
spec:
  containers:
  - name: probe-test
    image: tryoo0607/probe-test:latest
    ports:
    - containerPort: 8080
    startupProbe:
      httpGet:
        path: /startupz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 5
      timeoutSeconds: 3
      periodSeconds: 3
      failureThreshold: 5