apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe
  labels:
    app: probe-test
spec:
  containers:
  - name: probe-test
    image: tryoo0607/probe-test:latest
    env:
    - name: PROBE_DELAY_READINESS_SEC
      value: 30
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /readyz
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 3
      periodSeconds: 3
      failureThreshold: 5
