apiVersion: v1
kind: Pod
metadata:
  name: startup-probe
  namespace: test
  labels:
    app: probe-test
spec:
  containers:
  - name: probe-test
    image: tryoo0607/probe-test:latest
    env:
    - name: PROBE_DELAY_STARTUP_SEC
      value: "30"
    ports:
    - containerPort: 8080
    startupProbe:
      httpGet:
        path: /startupz
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 3
      periodSeconds: 3
      failureThreshold: 5
      