apiVersion: v1
kind: Pod
metadata:
  name: tcp-test
  labels:
    app: probe-test
spec:
  containers:
  - name: probe-test
    image: tryoo0607/probe-test:latest
    ports:
    - containerPort: 9090
    livenessProbe:
      tcpSocket:
        port: 9090
      initialDelaySeconds: 5
      timeoutSeconds: 3
      periodSeconds: 3
      failureThreshold: 5