apiVersion: v1
kind: Pod
metadata:
  name: exec-test
  namespace: test
  labels:
    app: probe-test
spec:
  containers:
  - name: probe-test
    image: tryoo0607/probe-test:latest
    env:
    - name: PROBE_DELAY_LIVENESS_SEC
      value: 30
    ports:
    - containerPort: 8080
    livenessProbe:
      exec:
        command:
        - /scripts/alive_check.sh
      initialDelaySeconds: 5
      timeoutSeconds: 3
      periodSeconds: 3
      failureThreshold: 5
